server:
    port: 8081

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/metadata
        username: metadata_user
        password: metadata_pass
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    kafka:
        bootstrap-servers: localhost:9092